#ifndef MODULE_IMAGE_UPSCALING_H_INCLUDED
#define MODULE_IMAGE_UPSCALING_H_INCLUDED




#define INPUT_ARRAY_LENGTH_D    (24)
#define INPUT_ARRAY_WIDTH_D     (32)
#define SCALING_FACTOR_D        (4)
#define OUTPUT_ARRAY_LENGTH_D   ((INPUT_ARRAY_LENGTH_D * SCALING_FACTOR_D) - SCALING_FACTOR_D)
#define OUTPUT_ARRAY_WIDTH_D    ((INPUT_ARRAY_WIDTH_D * SCALING_FACTOR_D) - SCALING_FACTOR_D)

void img_up_vUpscaleImage(uint16_t* pu16Array, float* fOutput);

#endif // MODULE_IMAGE_UPSCALING_H_INCLUDED
