function CreateFigure(X1, Y1, Array1, X2, Y2, Array2)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1, XDATA2, YDATA2, ZDATA2)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  XDATA2:  surface xdata
%  YDATA2:  surface ydata
%  ZDATA2:  surface zdata

%  Auto-generated by MATLAB on 11-Feb-2019 16:57:16

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);
colormap('hot');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',8,...
    'Position',[140001 29401 336000 252000],...
    'Units','pixels');
view(axes1,[180 90]);
hold(axes1,'on');

% Create axes
axes2 = axes('Parent',figure1,'FontSize',8,...
    'Position',[616001 29401 336000 252000],...
    'Units','pixels');
view(axes2,[180 90]);
hold(axes2,'on');

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.026875 0.178535825545171 0.422679924242424 0.704927310488058]);
view(axes3,[180 90]);
grid(axes3,'on');
hold(axes3,'on');

% Create surf
surf(X1,Y1,Array1,'Parent',axes3,'LineStyle','none');

% Create colorbar
colorbar('peer',axes3,'Position',...
    [0.941568813131312 0.170228452751817 0.0138888888888888 0.704927310488057]);

% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.495861742424242 0.178535825545171 0.416429924242424 0.702850467289719]);
view(axes4,[180 90]);
grid(axes4,'on');
hold(axes4,'on');

% Create surf
surf(X2,Y2,Array2,'Parent',axes4,'LineStyle','none');

